-- Secure Morphly admin, billing, analytics and operations schema.
-- Apply after schema.sql and admin_dashboard.sql.

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS account_status TEXT NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS suspended_by UUID,
  ADD COLUMN IF NOT EXISTS suspension_reason TEXT;

DO $$ BEGIN
  ALTER TABLE public.users ADD CONSTRAINT users_account_status_check
    CHECK (account_status IN ('active', 'suspended'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE public.credit_packages
  ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS is_recommended BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE public.credit_packages SET status = CASE WHEN is_active THEN 'active' ELSE 'paused' END
WHERE status IS NULL OR status NOT IN ('active', 'draft', 'paused');
DO $$ BEGIN
  ALTER TABLE public.credit_packages ADD CONSTRAINT credit_packages_status_check
    CHECK (status IN ('active', 'draft', 'paused'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE UNIQUE INDEX IF NOT EXISTS one_recommended_credit_package
  ON public.credit_packages (is_recommended) WHERE is_recommended = TRUE;

ALTER TABLE public.transactions
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS payment_gateway TEXT,
  ADD COLUMN IF NOT EXISTS gateway_transaction_id TEXT,
  ADD COLUMN IF NOT EXISTS gateway_fee_ngn NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS refund_status TEXT NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS package_id UUID REFERENCES public.credit_packages(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS package_name_snapshot TEXT,
  ADD COLUMN IF NOT EXISTS package_price_snapshot_ngn NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS package_credits_snapshot INTEGER,
  ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;
CREATE UNIQUE INDEX IF NOT EXISTS transactions_reference_unique ON public.transactions(reference) WHERE reference IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS transactions_gateway_id_unique ON public.transactions(payment_gateway, gateway_transaction_id)
  WHERE gateway_transaction_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.wallet_ledger (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  transaction_id UUID REFERENCES public.transactions(id) ON DELETE SET NULL, delta INTEGER NOT NULL,
  balance_after INTEGER NOT NULL CHECK (balance_after >= 0), entry_type TEXT NOT NULL,
  reason TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, actor_user_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.admin_audit_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), admin_user_id UUID NOT NULL,
  action TEXT NOT NULL, target_type TEXT NOT NULL, target_id TEXT, reason TEXT,
  before_data JSONB, after_data JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id UUID, installation_id TEXT,
  session_id UUID, platform TEXT, app_version TEXT, acquisition_source TEXT,
  event_name TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.error_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fingerprint TEXT NOT NULL,
  error_code TEXT NOT NULL, safe_message TEXT NOT NULL, user_id UUID, session_id UUID,
  platform TEXT, os_version TEXT, app_version TEXT, network_type TEXT, decart_stage TEXT,
  request_latency_ms INTEGER, severity TEXT NOT NULL DEFAULT 'error', occurrences INTEGER NOT NULL DEFAULT 1,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE UNIQUE INDEX IF NOT EXISTS error_logs_fingerprint_unique ON public.error_logs(fingerprint);

ALTER TABLE public.wallet_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins read wallet ledger" ON public.wallet_ledger;
DROP POLICY IF EXISTS "Admins read audit logs" ON public.admin_audit_logs;
DROP POLICY IF EXISTS "Admins read analytics" ON public.analytics_events;
DROP POLICY IF EXISTS "Admins read errors" ON public.error_logs;
CREATE POLICY "Admins read wallet ledger" ON public.wallet_ledger FOR SELECT USING (public.is_admin());
CREATE POLICY "Admins read audit logs" ON public.admin_audit_logs FOR SELECT USING (public.is_admin());
CREATE POLICY "Admins read analytics" ON public.analytics_events FOR SELECT USING (public.is_admin());
CREATE POLICY "Admins read errors" ON public.error_logs FOR SELECT USING (public.is_admin());

CREATE OR REPLACE FUNCTION public.admin_adjust_credits(p_admin UUID, p_user UUID, p_amount INTEGER, p_reason TEXT, p_key TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_old INTEGER; v_new INTEGER;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM admin_users WHERE user_id=p_admin AND is_active=TRUE) THEN RAISE EXCEPTION 'Admin access required'; END IF;
  IF p_amount <= 0 OR p_amount > 1000000 OR length(trim(p_reason)) < 3 THEN RAISE EXCEPTION 'Invalid adjustment'; END IF;
  IF EXISTS (SELECT 1 FROM wallet_ledger WHERE idempotency_key=p_key) THEN
    RETURN (SELECT jsonb_build_object('userId',user_id,'newCredits',balance_after,'duplicate',true) FROM wallet_ledger WHERE idempotency_key=p_key);
  END IF;
  SELECT credits INTO v_old FROM wallets WHERE user_id=p_user FOR UPDATE;
  IF v_old IS NULL THEN RAISE EXCEPTION 'Wallet not found'; END IF;
  v_new := v_old + p_amount;
  UPDATE wallets SET credits=v_new, updated_at=NOW() WHERE user_id=p_user;
  INSERT INTO wallet_ledger(user_id,delta,balance_after,entry_type,reason,idempotency_key,actor_user_id)
    VALUES(p_user,p_amount,v_new,'admin_adjustment',trim(p_reason),p_key,p_admin);
  INSERT INTO admin_audit_logs(admin_user_id,action,target_type,target_id,reason,before_data,after_data)
    VALUES(p_admin,'credits.added','user',p_user::text,trim(p_reason),jsonb_build_object('credits',v_old),jsonb_build_object('credits',v_new));
  RETURN jsonb_build_object('userId',p_user,'creditsAdded',p_amount,'newCredits',v_new);
END $$;

CREATE OR REPLACE FUNCTION public.admin_set_user_status(p_admin UUID, p_user UUID, p_status TEXT, p_reason TEXT)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_old TEXT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM admin_users WHERE user_id=p_admin AND is_active=TRUE) THEN RAISE EXCEPTION 'Admin access required'; END IF;
  IF p_status NOT IN ('active','suspended') OR length(trim(p_reason)) < 3 THEN RAISE EXCEPTION 'Invalid status change'; END IF;
  SELECT account_status INTO v_old FROM users WHERE id=p_user FOR UPDATE;
  UPDATE users SET account_status=p_status, suspended_at=CASE WHEN p_status='suspended' THEN NOW() ELSE NULL END,
    suspended_by=CASE WHEN p_status='suspended' THEN p_admin ELSE NULL END,
    suspension_reason=CASE WHEN p_status='suspended' THEN trim(p_reason) ELSE NULL END, updated_at=NOW() WHERE id=p_user;
  IF p_status='suspended' THEN UPDATE sessions SET status='ended',end_time=NOW() WHERE user_id=p_user AND status='active'; END IF;
  INSERT INTO admin_audit_logs(admin_user_id,action,target_type,target_id,reason,before_data,after_data)
    VALUES(p_admin,CASE WHEN p_status='suspended' THEN 'user.suspended' ELSE 'user.restored' END,'user',p_user::text,trim(p_reason),jsonb_build_object('status',v_old),jsonb_build_object('status',p_status));
  RETURN jsonb_build_object('userId',p_user,'status',p_status);
END $$;

REVOKE ALL ON FUNCTION public.admin_adjust_credits(UUID,UUID,INTEGER,TEXT,TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_set_user_status(UUID,UUID,TEXT,TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_adjust_credits(UUID,UUID,INTEGER,TEXT,TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_set_user_status(UUID,UUID,TEXT,TEXT) TO service_role;

CREATE OR REPLACE FUNCTION public.apply_verified_package_payment(
  p_user UUID, p_package UUID, p_reference TEXT, p_gateway_id TEXT, p_amount NUMERIC, p_fee NUMERIC DEFAULT 0
) RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_pkg credit_packages%ROWTYPE; v_old INTEGER; v_new INTEGER; v_tx UUID;
BEGIN
  IF current_setting('request.jwt.claim.role', true) IS DISTINCT FROM 'service_role' THEN RAISE EXCEPTION 'Service role required'; END IF;
  SELECT * INTO v_pkg FROM credit_packages WHERE id=p_package AND status='active' AND is_active=TRUE FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Package is unavailable'; END IF;
  IF p_amount < v_pkg.price_ngn THEN RAISE EXCEPTION 'Verified amount is below package price'; END IF;
  SELECT id INTO v_tx FROM transactions WHERE reference=p_reference OR (payment_gateway='flutterwave' AND gateway_transaction_id=p_gateway_id);
  IF v_tx IS NOT NULL THEN
    RETURN jsonb_build_object('status','success','duplicate',true,'transactionId',v_tx);
  END IF;
  SELECT credits INTO v_old FROM wallets WHERE user_id=p_user FOR UPDATE;
  IF v_old IS NULL THEN RAISE EXCEPTION 'Wallet not found'; END IF;
  v_new := v_old + v_pkg.credits;
  INSERT INTO transactions(user_id,type,amount_naira,credits,reference,status,payment_gateway,gateway_transaction_id,
    gateway_fee_ngn,package_id,package_name_snapshot,package_price_snapshot_ngn,package_credits_snapshot,verified_at)
  VALUES(p_user,'credit_purchase',p_amount,v_pkg.credits,p_reference,'success','flutterwave',p_gateway_id,
    COALESCE(p_fee,0),v_pkg.id,v_pkg.name,v_pkg.price_ngn,v_pkg.credits,NOW()) RETURNING id INTO v_tx;
  UPDATE wallets SET credits=v_new,updated_at=NOW() WHERE user_id=p_user;
  INSERT INTO wallet_ledger(user_id,transaction_id,delta,balance_after,entry_type,reason,idempotency_key)
    VALUES(p_user,v_tx,v_pkg.credits,v_new,'package_purchase','Verified Flutterwave payment','payment:'||p_reference);
  RETURN jsonb_build_object('status','success','transactionId',v_tx,'creditsAdded',v_pkg.credits,'newCredits',v_new);
END $$;
REVOKE ALL ON FUNCTION public.apply_verified_package_payment(UUID,UUID,TEXT,TEXT,NUMERIC,NUMERIC) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_verified_package_payment(UUID,UUID,TEXT,TEXT,NUMERIC,NUMERIC) TO service_role;
